#!/bin/bash

DIR=~/Development/Yieldmo-Porjects/tld/sql/src/pending/

if [ $1 == "" ]
then
    echo "You need give a file name"    
    exit 1
fi    

if [ -d "$DIR" ] 
then
    DATE=$(date +"%Y_%m_%d")
    FILE_NAME="${DATE}_${1}.sql" 
    FULL_FILE_NAME=$DIR$FILE_NAME
    touch $FULL_FILE_NAME
    subl $FULL_FILE_NAME
else
    echo 'The sql folder is not there, double check before you create a new sql file'
    exit 1
fi    
